### ISSUE TITLE
Cleanup sometimes run in the wrong directory

### ISSUE THREAD

**Issue by ldruschk** [enowars/action-cleanup-runner#4]
```
runner@gh-actions-runner:~/_work$ ls -alh
total 32K
drwxr-xr-x  8 runner runner 4.0K Apr 29 22:43 .
drwxr-xr-x 10 runner runner 4.0K Apr 29 21:57 ..
drwxr-xr-x  5 runner runner 4.0K Apr 29 22:41 _actions
drwxr-xr-x  3 runner runner 4.0K Apr 29 22:41 bambi-service-stonksexchange
drwxr-xr-x  3 runner runner 4.0K Apr 29 22:41 _PipelineMapping
drwxr-xr-x  3 runner runner 4.0K Apr 29 22:43 .pytest_cache
drwxr-xr-x  2 runner runner 4.0K Apr 29 22:43 _temp
drwxr-xr-x  3 runner runner 4.0K Apr 29 22:41 _tool
runner@gh-actions-runner:~/_work$ ls -alh bambi-service-stonksexchange/bambi-service-stonksexchange/
total 8.0K
drwxr-xr-x 2 runner runner 4.0K Apr 29 22:43 .
drwxr-xr-x 3 runner runner 4.0K Apr 29 22:41 ..
```

it appears that sometimes the cleanup step is being run while in the wrong working directory

https://github.com/enowars/bambi-service-stonksexchange/runs/2470470218?check_suite_focus=true

**Comment by christophwitzko** [comment]
`~/_work/bambi-service-stonksexchange/bambi-service-stonksexchange/` is the one that should be cleaned 🤔 
`~/_work` should stay untouched, it is also used for caching actions and tools.

**Comment by ldruschk** [comment]
Ah, ok. I just assumed that those directories should be cleared as well, since pip was using cached packages instead of fetching the newest versions. But after giving this some more thought, I think pip does actually search for the current version first and only uses the cached one if there is no newer version available, so this should not cause issues
